# Generated by Django 4.2.4 on 2024-03-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeCollections', '0002_collectionrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='collections',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
