# Generated by Django 4.2.4 on 2024-03-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeCollections', '0003_collections_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='published',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
