# Generated by Django 4.2.4 on 2023-12-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='content',
            field=models.CharField(max_length=700),
        ),
    ]
