# Generated by Django 4.2.4 on 2023-09-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='quantity_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
