# Generated by Django 4.2.4 on 2023-10-10 22:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0003_recipes_user_saverecipes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SaveRecipes',
            new_name='SavedRecipes',
        ),
    ]
