# Generated by Django 4.2.4 on 2023-10-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='quantity',
            field=models.CharField(default='', max_length=50),
        ),
    ]
