# Generated by Django 4.2.4 on 2024-03-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_recipes_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='cook_time',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='servings',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
