# Generated by Django 4.2.4 on 2024-03-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_recipes_cook_time_alter_recipes_servings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='published',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
