# Generated by Django 4.2.4 on 2024-03-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_recipes_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='category',
            field=models.CharField(blank=True, default='other', max_length=50),
        ),
    ]
