# Generated by Django 3.2.23 on 2024-05-09 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_alter_recipes_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='description',
            field=models.CharField(max_length=750),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='instructions',
            field=models.CharField(max_length=10000),
        ),
    ]
